#-------------------------------
# Site Settings
title: Sebastian Spiegel
description: 
logo: # You can add own logo. For example '/images/logo.png'.
logo_dark:


#-------------------------------
# Color Scheme Settings
color_scheme:
  default: dark # Default theme applied on the first visit (options: "light" or "dark")
  toggle: false # Enable theme toggle

# Enables or disables the theme toggle functionality:
# - true: Users can switch between light and dark modes using a toggle button.
#          The site will remember their choice for future visits.
# - false: The theme will always use the default mode specified above,
#          and the toggle button will not be displayed.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Academic Background'
      url: '/academic_background/'
    - title: 'About'
      url: '/about/'


#-------------------------------
# Author Settings
author:
  author_name: 
  author_avatar: 


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_avatar: /images/home/selfie.jpeg
  hero_title: Hello there!<br>I'm Sebastian ðŸ‘‹
  hero_subtitle: 
  hero_description: |
    I like using computers to solve physics and engineering problems. I also hold a PhD in theoretical physics. 
  hero_image: /images/home/DeskSetup.jpg
  hero_image_caption: 
  hero_button_text: Check out projects
  hero_button_link: '/projects/'

# Logos
logos:
  enable: false
  logos_title: Technologies
  logo_image:
    - alt: "Game Boy"
      image: "/images/1000.jpg"
    - alt: "Super Nintendo"
      image: "/images/1001.jpg"
    - alt: "Keyboard"
      image: "/images/1002.jpg"
    - alt: "Headphones"
      image: "/images/1003.jpg"
    - alt: "Mouse"
      image: "/images/1004.jpg"


#-------------------------------
# Section Blog Settings
blog:
  enable: false
  blog_title: Recent Projects


#-------------------------------
# Tags Section Settings
tags_section:
  enable: false
  tags_section_title: Hacker's Haven
  tags:
    - tag: "Programming"
      image: "/images/20.jpg"
    - tag: "Linux"
      image: "/images/21.jpg"
    - tag: "Productivity"
      image: "/images/22.jpg"
    - tag: "Security"
      image: "/images/23.jpg"


#-------------------------------
# Videos Section Settings
videos_section:
  enable: false
  videos_section_title: Latest Videos


#-------------------------------
# Gallery Section Settings
gallery_section:
  enable: false
  gallery_section_title: Byte Frame
  gallery:
    gallery_images:
      - alt: 'Rest'
        url: '/images/100.jpg'
        caption: 'Small steps lead to big results.'
      - alt: 'Lifestyle'
        url: '/images/101.jpg'
        caption: 'A peaceful moment captured during a serene evening.'
      - alt: 'Hobby'
        url: '/images/102.jpg'
        caption: 'True friends are like stars â€” they shine brightest when the world feels dark.'
      - alt: 'Computers'
        url: '/images/103.jpg'
        caption: 'Every click opens a new chapter in an endless story.'
      - alt: 'Games'
        url: '/images/104.jpg'
        caption: 'Every level is a new opportunity to test your limits.'

#-------------------------------
# Footer Settings
footer_description: You can reach me via any of the platforms below.


#-------------------------------
# Social Settings
social:
- {icon: "fa-solid fa-envelope", name: "Email", link: "mailto:your.email@example.com"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/spieseba"}
- {icon: "fa-brands fa-linkedin", name: "Linkedin", link: "https://linkedin.com/in/spieseba"}

# Example of adding a new link to the sidebar and footer - {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
contact:
  form_id: your@email.com # Add your form_id
  button_text: Send Now

# NOTE
# Coderon theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: false
  disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test
  disqus_title: Start the conversation
  disqus_button_text: Show Comments


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id